version: "2.1"

services:

  volume-service:
    build: .
    #restart: no
    command: >
         /bin/sh -c "echo 'SUCCESS'; trap : TERM INT; sleep infinity & wait"
    volumes:
    - ha-config:/sonoff-addon #same dir as specified in Dockerfile

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:2021.11.5"
    ports:
      - 80:8123
    volumes:
      - ha-config:/config
    depends_on:
      - volume-service  
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - mosquitto-conf:/mosquitto/config
    restart: unless-stopped
        
  node-red:
    container_name: node-red-ha
    environment:
      TZ: ${TZ}
    image: "aiwintermuteai/node-red-ha"
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/node-red-data   

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

volumes:
  ha-config:
  node-red-data:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
