version: "2"
volumes:
  config:
  ssh:
services:
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    network_mode: host
    privileged: true
    volumes:
      - config:/config
    devices:
      - /dev:/dev
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/zwave
  mqtt:
    image: arm64v8/eclipse-mosquitto
    ports:
      - 1883:1883
  ssh:
    build: ssh
    ports:
      - 2222:22/tcp
    volumes:
      - config:/config
      - ssh:/root/.ssh
    environment:
      HC_BASEPATH: /config
