version: "2.1"

volumes:
  config:
  mqtt:

services:
  # https://hub.docker.com/r/homeassistant/home-assistant
  app:
    build: app
    ports:
      - 80:8123
    volumes:
      - config:/config
    labels:
      io.balena.features.supervisor-api: 1

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data

  # https://hub.docker.com/r/causticlab/hass-configurator-docker
  configurator:
    image: causticlab/hass-configurator-docker:0.4.1
    ports:
      - 3218:3218/tcp
    volumes:
      - config:/config
    environment:
      HC_BASEPATH: /config
      HC_ENFORCE_BASEPATH: true
      HC_HASS_API: http://app:8123/api/

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:3.10.2
    command:
      - --port=8080
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 8080:8080/tcp
    volumes:
      - config:/config
    user: root
