name: versionist

on:
  push:
    branches:
      - "main"

jobs:

  versionist:
    if: "!contains(github.event.head_commit.author.name, 'versionist')"
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: tmigone/versionist@v0.4.6
        with:
          github_email: 'versionist@users.noreply.github.com'
          github_username: 'versionist'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
